name: Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  # Set the build number in MinVer.
  MINVERBUILDMETADATA: build.${{github.run_number}}
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  PROJECT_PATH: "Source/WageCalculator/WageCalculator.csproj"
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"

jobs:
  build:
    name: Build-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'
      - name: "Dotnet Tool Restore"
        run: dotnet tool restore
        shell: pwsh
      - name: "Dotnet Cake Build"
        run: dotnet cake --target=Build
        shell: pwsh
      - name: "Dotnet Cake Test"
        run: dotnet cake --target=Test
        shell: pwsh
      - name: "Dotnet Cake Pack"
        run: dotnet cake --target=Pack
        shell: pwsh
      - name: "Publish Artefacts"
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{matrix.os}}
          path: "./Artefacts"

  push-github-packages:
    name: "Push GitHub Packages"
    needs: build
    environment:
      name: "GitHub Packages"
      url: https://github.com/tramston/dotnet-wage-calculator/packages
    permissions:
      packages: write
    runs-on: windows-latest
    steps:
      - name: "Download Artefact"
        uses: actions/download-artifact@v3.0.0
        with:
          name: "windows-latest"
      - name: "Dotnet NuGet Add Source"
        run: dotnet nuget add source https://nuget.pkg.github.com/tramston/index.json --name GitHub --username tramston --password ${{secrets.GITHUB_TOKEN}}
        shell: pwsh
      - name: "Dotnet NuGet Push"
        run: dotnet nuget push .\*.nupkg --api-key ${{ github.token }} --source GitHub --skip-duplicate
        shell: pwsh

  push-nuget:
    name: "Push NuGet"
    runs-on: "windows-latest"
    needs: build
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'

      - name: "Restore packages"
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: "Build project"
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

      - name: "Get Version"
        id: version
        uses: battila7/get-version-action@v2

      - name: "Pack project"
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: "Push package"
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s ${{ env.NUGET_SOURCE_URL }} --skip-duplicate

